In [11]:
import numpy as np

def solve():
    global ins
    global gs
    move=0
    while(ins!=gs):
        poss_routes,z_arr=possible_routes(ins)
        curr_manhattan_distance=100000
        best_move=[]
        for i in poss_routes:
            ins[i[0]][i[1]],ins[z_arr[0]][z_arr[1]]=ins[z_arr[0]][z_arr[1]],ins[i[0]][i[1]]
            sum_manhattan_distance=0
            for j in range(3):
                for k in range(3):
                    if(ins[j][k]!=0):
                        sum_manhattan_distance+=manhattan_distance(ins,gs,ins[j][k])
            if(sum_manhattan_distance<curr_manhattan_distance):
                curr_manhattan_distance=sum_manhattan_distance
                best_move=i
            ins[i[0]][i[1]],ins[z_arr[0]][z_arr[1]]=ins[z_arr[0]][z_arr[1]],ins[i[0]][i[1]]
        ins[best_move[0]][best_move[1]],ins[z_arr[0]][z_arr[1]]=ins[z_arr[0]][z_arr[1]],ins[best_move[0]][best_move[1]]
        move+=1
        print(np.array(ins))
    print(f'total moves: {move}')
    
def manhattan_distance(ins,gs,num):
    insarr=[]
    gsarr=[]
    for i in range(3):
        for j in range(3):
            if(ins[i][j]==num):
                insarr=[i,j]
            if(gs[i][j]==num):
                gsarr=[i,j]

    distance=abs(insarr[0]-gsarr[0])+abs(insarr[1]-gsarr[1])
    
    return distance

ins=[[1,2,3],
    [0,4,6],
    [7,5,8]]

gs=[[1,2,3],
    [4,5,6],
    [7,8,0]]

manhattan_distance(ins,gs,2)

def possible_routes(ins):
    z_arr=[]
    for i in range(3):
        for j in range(3):
            if(ins[i][j]==0):
                z_arr=[i,j]
                break
    poss_routes=[]
#     up
    if((z_arr[0]-1)>=0):
        poss_routes.append([z_arr[0]-1,z_arr[1]])
#     down
    if(z_arr[0]+1<3):
        poss_routes.append([z_arr[0]+1,z_arr[1]])
#         right
    if(z_arr[1]+1<3):
        poss_routes.append([z_arr[0],z_arr[1]+1])
#         left
    if(z_arr[1]-1>=0):
        poss_routes.append([z_arr[0],z_arr[1]-1])
    return poss_routes,z_arr

possible_routes(ins)



    
solve()  
np.array(ins)

[[1 2 3]
 [4 0 6]
 [7 5 8]]
[[1 2 3]
 [4 5 6]
 [7 0 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
total moves: 3


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])