MAGIC SQUARE

In [1]:
import numpy as np

def generateMagicSquare(size):
    Matrix = np.zeros((size,size), dtype = int) # zeros size of matrix
    num = 1       # starting number
    i = 0         # row index
    j = size//2   # column index
    
    while num <= size**2:     # filling the matrix
        Matrix[i][j] = num   
        num+=1
        ni = (i-1)%size      # next move 
        nj = (j+1)%size      # next move
        if Matrix[ni,nj]:    # if there is any value in the place it will move down
            i+=1
        else:                # otherwise it will place next num in up right side
            i = ni
            j = nj
    print(Matrix)
    
size = int(input("Enter size of matrix: "))
generateMagicSquare(size)

Enter size of matrix: 4


IndexError: index 4 is out of bounds for axis 0 with size 4

SUDOKU

In [31]:
size = 9
Matrix = np.array([[0,0,0,3,0,1,0,9,0], [5,0,0,6,0,0,1,0,0],[0,0,9,0,0,0,0,0,8], [0,0,0,7,0,0,0,3,0], [0,7,4,2,0,8,0,0,0], [0,0,5,0,0,9,0,0,6], [0,0,0,5,0,0,0,0,0],[0,6,0,0,0,0,0,7,3],[0,0,0,0,7,0,8,0,0]])
print(Matrix)

def checkrow(grid,row,num):
    for(i in range(9)):
        if(Matrix[row][i]==num):
            return -1

def checkcolumnm(grid,col,num):
    for(i in range(9)):
        if(Matrix[i][col]==num):
            return -1
def checkbox(Matrix, row, col, num):
    for i in range(3 *(row//3)):
        for j in range(3 *(col//3)):
            if(Matrix[i][j]==num):
                return -1
    

[[0 0 0 3 0 1 0 9 0]
 [5 0 0 6 0 0 1 0 0]
 [0 0 9 0 0 0 0 0 8]
 [0 0 0 7 0 0 0 3 0]
 [0 7 4 2 0 8 0 0 0]
 [0 0 5 0 0 9 0 0 6]
 [0 0 0 5 0 0 0 0 0]
 [0 6 0 0 0 0 0 7 3]
 [0 0 0 0 7 0 8 0 0]]


In [37]:
Matrix = np.array([0,0,0,3,0,1,0,9,0])
for i in range(9):
    if(Matrix[i]==3):
        print("Hello")

Hello
